name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings"
  Z3_RELEASE: 'z3-4.8.12'
  RUST_BACKTRACE: 'full'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        link: [default, static, system]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      if: ${{ matrix.link != 'static' }}

    - name: Checkout with submodules
      uses: actions/checkout@v2
      if: ${{ matrix.link == 'static' }}
      with:
        submodules: recursive

    - name: Uninstall Z3 on Linux for non-system builds
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.link != 'system' }}
      run: sudo apt-get remove libz3-dev

    - name: Install Z3 on Windows for system builds
      if: ${{ matrix.os == 'windows-latest' && matrix.link == 'system' }}
      run: |
        curl.exe -L "https://github.com/Z3Prover/z3/releases/download/${env:Z3_RELEASE}/${env:Z3_RELEASE}-x64-win.zip" -o "./${env:Z3_RELEASE}-x64-win.zip"
        tar -xf "./${env:Z3_RELEASE}-x64-win.zip"
        echo "${PWD}\${env:Z3_RELEASE}-x64-win\bin" >> $env:GITHUB_PATH
        echo "LIB=${PWD}\${env:Z3_RELEASE}-x64-win\bin" >> $env:GITHUB_ENV

    - name: Test with Z3 releases
      if: ${{ matrix.link  == 'default' }}
      run: cargo test --lib -vv

    - name: Test with Z3 system installation
      if: ${{ matrix.link == 'system' }}
      run: cargo test --lib -vv --features dynamic-link-z3

    - name: Test with static Z3 builds
      if: ${{ matrix.link  == 'static' }}
      run: cargo test --lib -vv --features static-link-z3
